#
# TABLE STRUCTURE FOR: apartments
#

DROP TABLE IF EXISTS `apartments`;

CREATE TABLE `apartments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_guests_number` int(10) unsigned NOT NULL,
  `types` enum('private room','entire home') COLLATE utf8_unicode_ci NOT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `photo_id` int(10) unsigned NOT NULL,
  `city_id` varchar(130) COLLATE utf8_unicode_ci DEFAULT NULL,
  `prix` double NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Apartments';

INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (1, 5, 'private room', 'Dolores omnis repellendus est. Quam minima tempora alias dolorum. Tempora iusto non in minima.', 72, '30', '362');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (2, 4, 'entire home', 'Natus nisi esse tempora maxime enim soluta provident. Voluptatem rerum repudiandae praesentium officiis doloribus laboriosam et quis. Non soluta aperiam et impedit. Ut voluptas provident quisquam nesciunt.', 75, '19', '496');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (3, 6, 'entire home', 'Est voluptas earum est sed eveniet at. Iusto officia similique facere facere aut.', 51, '18', '85');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (4, 6, 'entire home', 'Quisquam nihil a quo nulla ratione incidunt. Voluptas numquam atque qui architecto sunt placeat. Ipsam eum vel quam fugiat reiciendis. Ut eum dolorem repellat voluptatem ratione accusantium at.', 43, '51', '228');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (5, 8, 'entire home', 'Asperiores nobis rerum quia rerum. Omnis ratione qui dolores voluptas id. Corrupti et ut voluptatum amet. Illum ut reprehenderit quis ut aut reiciendis.', 19, '81', '196');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (6, 5, 'entire home', 'Velit similique recusandae consequatur. Dolorum dolores nam ullam quia nisi non. Doloremque voluptatem dolorem eligendi beatae maxime. Possimus nihil aut eaque.', 38, '75', '429');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (7, 4, 'entire home', 'Veniam magnam aliquid cupiditate ad placeat. Recusandae qui dignissimos et voluptatem quasi hic exercitationem eos. Esse asperiores quaerat molestias quaerat.', 57, '69', '335');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (8, 10, 'entire home', 'Ea sequi qui quia deleniti rerum non. Velit aut libero inventore ut officiis iusto. Ea quia distinctio quia recusandae aspernatur perferendis exercitationem voluptas.', 86, '63', '215');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (9, 1, 'entire home', 'Neque laboriosam provident incidunt. Qui sapiente incidunt vel deserunt qui fugit eum sit.', 90, '53', '440');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (10, 7, 'private room', 'At odit distinctio cum molestiae et. Et nihil debitis dolorem nisi. Impedit at quos non in blanditiis debitis odio.', 1, '56', '110');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (11, 9, 'entire home', 'Quis facilis molestias culpa dignissimos quo aspernatur. Occaecati ex libero eos.', 54, '35', '134');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (12, 8, 'private room', 'Minima atque ut sint ducimus fugiat. Nemo quae nisi omnis ut ea et velit. Sint et laboriosam deleniti dolor aut est magnam rerum. Assumenda rerum dolores ut nesciunt harum neque rerum.', 52, '17', '116');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (13, 9, 'entire home', 'Nobis alias est ullam dicta. Quis est quibusdam nesciunt ex ea distinctio. Vitae iure natus et repellat eius et.', 3, '74', '380');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (14, 8, 'entire home', 'Tempore et est quam aut rem minus nihil rerum. Sed libero ut et cumque. Aut tempora pariatur id itaque quos similique consequuntur ut. Ab tempore ipsam id fugit et.', 70, '83', '427');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (15, 1, 'entire home', 'Rerum nulla fugiat perspiciatis. Tempore qui placeat blanditiis optio delectus nobis et molestiae. Dolorem dolor id et aut. Fugiat provident similique ipsam ut saepe veniam commodi.', 49, '76', '392');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (16, 7, 'private room', 'A dolores sunt provident recusandae. Ratione non dolores placeat quae. Aliquam suscipit repellendus blanditiis adipisci dicta eum nulla eligendi.', 27, '76', '458');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (17, 8, 'entire home', 'Voluptas et molestias iure architecto suscipit id. Sit nihil aliquid est sapiente veniam quibusdam hic. Optio eum fuga consequatur ad autem. Dolor enim et maxime dolorem nihil doloribus.', 12, '48', '214');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (18, 5, 'entire home', 'Praesentium est provident a odio. Quo sit in dignissimos quae numquam delectus provident. Commodi est corporis exercitationem esse natus deserunt. Ea est enim est asperiores quia laboriosam autem.', 5, '51', '299');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (19, 7, 'entire home', 'Qui amet omnis sunt velit. Ratione aspernatur at ut aliquid eveniet voluptatum cumque earum. Ex quia facilis corrupti repudiandae ratione earum. Molestiae incidunt molestias ipsam at iste qui nemo ducimus.', 41, '56', '363');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (20, 1, 'private room', 'Et ut et fuga consequatur. Sit incidunt eos reiciendis sed. Deserunt nesciunt vel velit eum. Ea odio numquam sapiente at optio nam quisquam.', 55, '37', '460');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (21, 10, 'private room', 'Debitis ex ipsam consequatur dolorum omnis voluptas possimus. Quibusdam cum sed facilis nobis dicta minus doloremque. Sunt saepe praesentium est voluptate numquam quo quisquam dolores.', 10, '38', '187');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (22, 7, 'private room', 'Velit alias sapiente accusantium quaerat ipsum facilis aut. Repudiandae ipsa earum sit sint.', 23, '16', '86');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (23, 7, 'private room', 'Tempora aliquam aut est. Assumenda ex quidem qui voluptas et sit animi voluptatem. Cumque quia quia pariatur a adipisci quod earum. Dicta quam excepturi dolore sapiente sint omnis pariatur aut.', 15, '32', '340');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (24, 1, 'private room', 'Hic quod voluptate id. Quia quia blanditiis tempora sit ut. Iusto sunt nemo dolores.', 33, '85', '199');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (25, 8, 'private room', 'Cumque dolores aut ut. Corporis modi maxime nam. Amet nesciunt laborum nemo saepe numquam et laudantium rem.', 58, '16', '307');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (26, 4, 'entire home', 'Nihil in et hic suscipit veniam. Optio accusamus dicta quasi qui voluptatum animi.', 39, '80', '417');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (27, 3, 'private room', 'Sed veniam et adipisci eum modi voluptas cupiditate. Quis libero beatae non esse sint aliquid. Aliquam et incidunt voluptatem alias. Fuga magnam repellendus a ratione. Voluptatem sit enim in eius a itaque.', 73, '96', '160');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (28, 2, 'entire home', 'Beatae et fuga tempore hic et natus dolor. Nostrum voluptates facere deleniti minus sed a.', 27, '96', '323');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (29, 3, 'entire home', 'Labore provident officiis et eum distinctio dolores. Omnis et voluptas corporis officiis. Et qui commodi consequuntur quasi accusantium et voluptatem. Amet debitis error consequatur dolore repellendus consectetur modi corrupti.', 31, '71', '344');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (30, 3, 'entire home', 'Architecto nostrum doloremque minus ipsum. Facilis et nostrum qui aliquam modi in architecto. Facere qui et nesciunt totam consequatur autem et neque. Deleniti quisquam necessitatibus necessitatibus voluptatibus. Impedit fugit placeat voluptatem eius ipsum.', 59, '60', '158');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (31, 3, 'entire home', 'Hic sit et asperiores animi suscipit. Sit libero molestias non culpa aliquid et dolorem eveniet. Expedita ad laborum nisi et.', 45, '44', '82');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (32, 3, 'private room', 'Voluptatem officiis deserunt vel ut perferendis. Maxime qui ea voluptas sunt perferendis assumenda. Exercitationem minus sequi molestias. Est omnis eum et asperiores.', 63, '25', '393');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (33, 4, 'private room', 'Dignissimos eligendi nulla provident facere sunt nihil eum. Consequatur rerum illo voluptates aut vitae totam. Fuga accusamus optio possimus dolor non quia magnam.', 8, '11', '231');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (34, 1, 'entire home', 'Et voluptates labore eum ipsam. Earum omnis accusantium qui eum eligendi libero ea. Magni reiciendis id quas distinctio sint similique repudiandae. Ut soluta rerum et maiores natus. Explicabo possimus similique accusamus sunt cum fuga illo.', 37, '72', '369');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (35, 8, 'private room', 'Modi aut saepe corrupti quas. Quas consequatur sit ut. Labore et fugiat unde et. Deserunt a nemo enim officiis. Enim ad pariatur voluptatem voluptas voluptatem perferendis facere.', 97, '14', '278');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (36, 1, 'private room', 'Totam vel facilis voluptate sint. Fugit et non voluptatem nesciunt omnis qui autem sed.', 72, '65', '182');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (37, 10, 'private room', 'Possimus reprehenderit porro enim dolores voluptas et. Quia culpa et et quia. Quia facilis consequatur aspernatur nostrum ipsum.', 19, '47', '302');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (38, 8, 'entire home', 'Rerum omnis qui perferendis et aut non. Quos aut asperiores quas tenetur sed.', 96, '72', '170');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (39, 9, 'private room', 'Perspiciatis et consequuntur distinctio nemo dolorum qui exercitationem. Et repellendus dolores doloremque dicta aut fugiat consequuntur. Voluptates dolor pariatur veritatis vero aliquid assumenda nemo.', 80, '14', '494');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (40, 6, 'entire home', 'Molestias iusto ad magni odit. Qui non reprehenderit dolorem assumenda. Est dolorem aut dolore et ut dolorem.', 65, '6', '487');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (41, 3, 'entire home', 'Tempore velit ea ipsum. Aut dolore adipisci ut blanditiis alias voluptatem sequi. Voluptatem temporibus dolore illo numquam consequatur. Nostrum consequatur qui voluptatibus consequatur inventore sed. Porro quae accusamus occaecati nobis ut.', 11, '94', '103');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (42, 3, 'entire home', 'Perspiciatis sed minus voluptas non quisquam. Pariatur necessitatibus laborum veniam ratione debitis quae dolorem. Magni harum quia explicabo sapiente maiores nulla. Et non temporibus nobis reprehenderit vitae ipsa tempore. Laborum velit et perferendis inventore.', 50, '77', '470');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (43, 6, 'entire home', 'Dolore quia doloribus amet vel at est dolorem magnam. Quibusdam laboriosam molestiae quae quibusdam repudiandae qui ab porro. Et veritatis ea nihil animi fugiat. Dolor omnis saepe animi rerum architecto sint.', 23, '43', '486');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (44, 4, 'entire home', 'Est modi laborum soluta recusandae molestias. Porro at ratione quasi nemo architecto eos sunt est. Culpa occaecati temporibus magni pariatur necessitatibus porro.', 9, '92', '191');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (45, 3, 'private room', 'Similique officia labore quis hic sapiente impedit. Recusandae et eum dolorum dolorum ut illo. Dolores quisquam quis placeat. Voluptates sequi natus ullam velit. Vitae quis reprehenderit eaque autem.', 20, '8', '217');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (46, 6, 'entire home', 'Sed esse rem dicta dolor officia. Ea dolorum explicabo eos voluptas. Tempore et aspernatur necessitatibus et.', 99, '93', '203');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (47, 2, 'private room', 'Dolorum est unde beatae magnam minus. Recusandae iusto dolores molestiae aut numquam aperiam.', 91, '9', '256');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (48, 4, 'private room', 'Earum expedita illo et ut aut ut. Quasi et in sed dicta sed est cum. Rerum iure minus modi cum soluta nihil.', 67, '82', '126');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (49, 10, 'entire home', 'Aut eveniet quo ut voluptas sint sit distinctio placeat. Consequatur tenetur beatae voluptatem nam. Consequatur dolores nulla laudantium odit. Rem veniam libero voluptatibus quis est ipsa.', 14, '27', '338');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (50, 1, 'entire home', 'Consequatur voluptatem deserunt nostrum ea iste perferendis. Iste dolore et ipsam cumque qui dolores porro. Eius voluptas deleniti voluptates nesciunt voluptates aut consequatur inventore. Officiis itaque nemo autem cumque id.', 81, '18', '120');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (51, 9, 'private room', 'Nihil saepe officia non voluptas voluptatibus. Voluptate ut est quos non fugiat non. Sequi eius dolor consequatur ducimus.', 51, '80', '407');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (52, 3, 'entire home', 'Iusto dicta consectetur omnis culpa rem facere alias. Aut ea iste tempora ducimus quae. Rerum est aperiam rerum blanditiis et. Delectus in ut sed voluptas molestiae dolores delectus. Aliquid voluptatem omnis qui iusto in.', 12, '55', '296');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (53, 6, 'entire home', 'Ipsam amet voluptatibus est deleniti cumque iusto id. Nihil officia eligendi qui veritatis aut sed.', 87, '19', '345');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (54, 2, 'entire home', 'Necessitatibus ut dolor sequi sed quasi. Voluptas laboriosam dolor porro aut rerum eaque. Voluptates nihil non reiciendis ut delectus.', 80, '64', '474');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (55, 10, 'private room', 'Doloremque alias quo quam voluptas omnis illo porro blanditiis. Fugiat perspiciatis voluptate quae. Molestiae libero reiciendis architecto est debitis officia. Molestiae quo non et totam.', 57, '3', '119');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (56, 1, 'private room', 'Dolorem neque placeat occaecati. Recusandae est quo nostrum itaque. Sit dolores adipisci necessitatibus ipsa aut. Labore provident consequatur quae porro et. Et sit in exercitationem explicabo recusandae occaecati.', 61, '70', '369');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (57, 10, 'private room', 'Soluta temporibus aut facere ad quod. Iusto ipsam itaque vel distinctio cum. Autem veritatis et porro laudantium laudantium. Ipsa ipsum earum ut et facilis.', 14, '21', '234');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (58, 3, 'private room', 'Ad nihil voluptate dolor culpa quisquam consequatur quod. Et nesciunt voluptatem beatae sunt. Sed fugit voluptatem nostrum veniam qui.', 13, '33', '142');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (59, 10, 'entire home', 'Deleniti doloribus laboriosam voluptas. Harum quasi tempora voluptate quas exercitationem voluptas inventore. Iste corporis deserunt iure aliquid sed. Doloremque non impedit temporibus rerum consequatur est.', 64, '85', '202');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (60, 8, 'entire home', 'Et et quas molestiae eos ducimus. Omnis perferendis sapiente illum iste ut error non. Consequuntur non facilis voluptatem.', 57, '26', '103');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (61, 6, 'private room', 'Laboriosam quaerat vel aut. Iure modi assumenda praesentium ea et quidem ut. Possimus laborum mollitia aut quisquam.', 70, '17', '332');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (62, 8, 'private room', 'Explicabo sed dicta rem voluptates. Eos sit quam qui. Aut nihil dolor ex placeat repellat libero et nihil.', 90, '86', '312');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (63, 1, 'private room', 'Nam illo et aut expedita assumenda culpa at. Et soluta et omnis harum dignissimos est. Fugit voluptatum modi eos neque ipsam quod saepe. Repellat qui nostrum iure deleniti eum.', 19, '89', '194');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (64, 5, 'entire home', 'Delectus vel corrupti nesciunt aut. Rerum aut aut enim minima magni natus totam. Esse ut eos at molestias ut quidem.', 90, '54', '448');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (65, 8, 'entire home', 'Tempore omnis quos quam mollitia nisi perspiciatis cum. Totam vero sint aspernatur.', 3, '31', '486');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (66, 7, 'private room', 'Eos deserunt vero quo voluptatibus est. Voluptatum repellat sint magni. Ratione eveniet cupiditate sit quaerat. Recusandae quis et aut qui voluptas quisquam qui.', 2, '60', '402');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (67, 5, 'entire home', 'Esse sed delectus consequatur atque. Atque rem expedita et. Ea ipsam dignissimos itaque officiis cumque ab provident cupiditate. Dolore est molestiae consectetur vitae ipsam.', 1, '52', '164');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (68, 7, 'private room', 'Consequuntur et officia nam. Quis placeat et est est nesciunt repudiandae. Quae amet consequatur numquam. Enim ea beatae accusamus odit expedita.', 97, '84', '99');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (69, 7, 'entire home', 'Itaque ut quia repellat ex. Et et qui expedita illum voluptatum. Qui tenetur officiis doloribus recusandae. Dolorem quo facere distinctio. In provident qui voluptas placeat a.', 52, '27', '255');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (70, 3, 'entire home', 'Consectetur sequi enim laudantium et repellendus sunt. Aut et qui et delectus voluptas eveniet. Reprehenderit possimus delectus est laudantium sed quis. Tempora aut ut qui vitae et.', 17, '78', '385');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (71, 3, 'entire home', 'Dolorem quaerat et in est enim laudantium. Aut sint repellat dolorem dolore est eveniet. Omnis nulla praesentium sequi tempora. Totam illum et iste dignissimos aliquam voluptas non. Ipsam est dolorem nobis dolores non nihil temporibus.', 59, '55', '325');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (72, 1, 'entire home', 'Aliquam at ducimus provident suscipit. Vel sit vero iure quis dicta. Voluptates placeat dolorem ipsa.', 83, '49', '403');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (73, 1, 'entire home', 'Distinctio molestiae laborum similique magnam est cupiditate a. Adipisci aspernatur officia nulla non possimus aut perspiciatis.', 15, '92', '476');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (74, 9, 'private room', 'Velit ut distinctio et consequatur quia autem. Autem deleniti eligendi accusamus qui.', 39, '63', '146');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (75, 7, 'entire home', 'Laboriosam nisi omnis sunt non aperiam sunt. Ut officia facere mollitia qui id. Dicta ut temporibus pariatur voluptatum quis libero iste cumque.', 14, '27', '457');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (76, 10, 'entire home', 'A quo iusto harum veritatis. A facilis ut aut consequatur. Quia aperiam ut aut in voluptatem expedita voluptatum. Occaecati error voluptate sit voluptatem.', 100, '88', '180');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (77, 10, 'entire home', 'Debitis labore dolorem nemo corporis veniam voluptatibus ut. Est magni enim ut commodi nihil reprehenderit eum. Sed voluptate exercitationem iure voluptatem eos. Similique necessitatibus aspernatur aperiam est.', 66, '51', '484');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (78, 9, 'entire home', 'Enim quo culpa accusamus vel. Impedit enim sunt ex non ut. Asperiores explicabo animi sint eius voluptatem numquam aut.', 97, '20', '437');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (79, 7, 'entire home', 'Aliquam qui consequuntur est ut voluptas dolore aliquam eaque. Dolorem corrupti sint ipsum.', 23, '62', '229');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (80, 7, 'entire home', 'Perspiciatis eligendi numquam ad odit. Porro ea qui laboriosam maiores quia. Enim accusantium et earum et. Qui sit laborum et odio minima blanditiis quia doloribus.', 29, '28', '196');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (81, 9, 'entire home', 'Quia aspernatur fugit enim odit suscipit. Eligendi minima eos quia tempora reprehenderit. Architecto nihil omnis maxime accusantium. Nam nemo consequatur architecto vitae consectetur eos. Autem aperiam explicabo facilis voluptates consequatur rem ab.', 19, '52', '442');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (82, 9, 'private room', 'Aspernatur nostrum sequi atque aut nobis ut porro aut. Facilis et sed quam culpa et quas.', 83, '91', '355');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (83, 5, 'entire home', 'Minus consequatur magni ducimus neque odio. A qui fugiat et animi. Voluptatibus voluptates eum eligendi voluptas perspiciatis.', 40, '71', '496');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (84, 10, 'entire home', 'Omnis sed provident illum quod eius. Non voluptas quis necessitatibus deleniti corrupti. Incidunt porro ut quam occaecati harum dolores.', 68, '96', '157');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (85, 5, 'entire home', 'Quis illo ullam consequatur doloribus accusantium similique dignissimos molestiae. Vitae iure aut illum rem. Qui voluptatem asperiores incidunt sed aliquam quae repudiandae.', 49, '69', '306');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (86, 10, 'entire home', 'In quia placeat aspernatur quasi rem deleniti quasi. Dolores magni fuga qui nemo voluptas aspernatur nihil. Soluta veritatis saepe ut delectus. Minus quisquam iure voluptatem aut quis.', 41, '45', '316');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (87, 7, 'entire home', 'Exercitationem suscipit id est repudiandae odio et magnam. Maiores eligendi ut officia at. Libero non est pariatur similique at sint. Autem culpa impedit debitis.', 96, '32', '453');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (88, 6, 'private room', 'Accusantium sit ut est voluptatem earum. Et et natus unde facere ducimus tempore voluptatem assumenda. Molestiae a delectus doloremque at magnam officiis. Non corrupti cupiditate labore dignissimos ea sed expedita totam.', 88, '76', '456');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (89, 8, 'private room', 'Autem dolor et vero. Voluptas consequatur fugiat quod porro. Quo ut autem quas natus aut. Et excepturi numquam enim quod est corrupti amet.', 62, '29', '221');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (90, 5, 'entire home', 'Quas natus sunt dolor autem ipsa. Commodi atque dolore suscipit hic sed. Assumenda provident fugiat aut eos. Repellendus voluptates similique aut quo dolor ex qui.', 44, '39', '126');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (91, 7, 'private room', 'Culpa blanditiis eligendi beatae deserunt quis ut. Sint voluptatem mollitia corrupti temporibus. Itaque hic non dignissimos iure.', 56, '52', '372');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (92, 2, 'private room', 'Non harum eaque architecto aperiam. Iusto sit quo impedit possimus dolorem. Ea sit omnis eos est. Voluptas rem qui in dolor eos impedit.', 69, '41', '179');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (93, 5, 'entire home', 'Quo nemo rerum ut. Aliquid molestias unde explicabo eum voluptate deleniti alias officiis. Sequi sapiente dolorum maiores a.', 40, '47', '492');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (94, 5, 'entire home', 'Facilis aut aliquam est quia est nobis. Aut deserunt eligendi voluptates quia consequatur. Quam voluptatem vel facilis quia.', 61, '81', '131');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (95, 9, 'private room', 'Consectetur et magnam illo inventore voluptatem. Quae eveniet voluptatum voluptatibus. Aut sed aut ab eaque.', 76, '53', '395');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (96, 9, 'entire home', 'Tenetur perspiciatis mollitia ut enim. Vel quis necessitatibus alias omnis veritatis totam voluptate similique. Et unde cum laborum fuga ut unde.', 99, '33', '422');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (97, 7, 'private room', 'Fugiat nihil non fugit tempore consequatur officiis harum. Eveniet molestias harum veritatis autem ratione ducimus. Recusandae non fugiat voluptas laborum. Commodi eum natus laborum quibusdam fuga.', 4, '83', '446');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (98, 7, 'entire home', 'Sunt nemo vero suscipit eum quia nihil. Similique molestiae dolorem tenetur voluptatem ipsa. Voluptatibus reiciendis qui et consequatur consectetur nihil.', 29, '86', '431');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (99, 3, 'private room', 'Nesciunt architecto corrupti ea sed voluptatem odit. Sit atque molestias occaecati. Dicta commodi blanditiis adipisci eum asperiores. Ut ea nesciunt id beatae eos ab.', 83, '49', '403');
INSERT INTO `apartments` (`id`, `id_guests_number`, `types`, `body`, `photo_id`, `city_id`, `prix`) VALUES (100, 8, 'entire home', 'Natus sit accusamus doloribus iure. Quis et aut perferendis vel voluptatum tempore. Ut ex et dolorem suscipit dolorem ratione. At autem corporis quas architecto repudiandae corrupti quo.', 14, '28', '389');


